import PropTypes from 'prop-types';

export const BuildingType = PropTypes.shape({
  id: PropTypes.number.isRequired,
  building_name: PropTypes.string.isRequired,
  neighborhood_name: PropTypes.string.isRequired,
  building_id: PropTypes.number,
  building_website_url: PropTypes.string,
  description: PropTypes.string,
  client_website_neighborhood_id: PropTypes.number,
  building_type: PropTypes.string.isRequired,
  instagram_account: PropTypes.string,
  position: PropTypes.number.isRequired,
  image_urls: PropTypes.arrayOf(PropTypes.string),
  video_url: PropTypes.string,
  address: PropTypes.string,
  property_type: PropTypes.string,
  price_min: PropTypes.number,
  price_max: PropTypes.number,
  beds_min: PropTypes.number,
  beds_max: PropTypes.number,
  baths_min: PropTypes.oneOfType([PropTypes.number, PropTypes.string]),
  baths_max: PropTypes.oneOfType([PropTypes.number, PropTypes.string]),
  features: PropTypes.arrayOf(PropTypes.string),
  total_units: PropTypes.number,
  total_stories: PropTypes.number,
  year_built: PropTypes.number,
  occupancy_starting_description: PropTypes.string,
});
