export const ListingMock = {
  assessed_value: [0, 0],
  skyline_view: true,
  building_rooftop: true,
  concession: null,
  playroom: null,
  live_in_super: true,
  floor_number: 20,
  exclusions: null,
  den: true,
  under_contract: false,
  home_offices: null,
  external_media: [],
  last_updater: 'listing_history_writer',
  multimedia_types: [],
  vow_consumer_comment: false,
  sides_per_buy_side_agent: 0,
  large_image: null,
  lease_term_max_months: null,
  state: 'NY',
  num_bedrooms: 4,
  hoa_fee_s: '8867',
  parent_geography_id: 1762,
  water_view: null,
  must_be_prewar: false,
  buyers_agent2_id: null,
  region_id: 1278,
  above_area_square_ft: 6744,
  agent_first_name: 'Kyle W.',
  new_development: false,
  bbl: 1011147503,
  buyers_agent2_email: null,
  flip_tax_description: null,
  virtual_tour_url: null,
  property_usage: null,
  courtyard: true,
  updated_by: null,
  billiards_room: null,
  price_last_changed: null,
  beds: '4',
  inclusions: null,
  general_condition: 'mint',
  commission_total: 2,
  floor_descriptions: null,
  electric_car_chargers: null,
  eat_in_kitchen: null,
  syndication: {},
  unit_laundry_allowed: false,
  buyers_agent1_id: null,
  north_exposure: null,
  latitude: '40.769861',
  total_pending_updates: 0,
  address_display: null,
  has_fireplace: true,
  view_array: ['Park', 'Skyline'],
  open_listing: null,
  details_last_updated: '2012-02-15T00:00:00.000-05:00',
  garage_spaces: null,
  searchable_property_type_code: 540,
  updated_at: '2020-07-30T16:22:17.886-04:00',
  furnished: null,
  pet_policy: null,
  property_type: 'Condo',
  region_name: 'New York City',
  building_name: '',
  deposit_amount: null,
  address: '15 Central Park West',
  sprinklers: null,
  address_with_unit: '15 Central Park West PH20',
  address_with_unit_hashed: '15 Central Park West #PH20',
  listing_url: 'http://www.brownharrisstevens.com',
  sponsored: false,
  canonical_neighborhood_name: 'Lincoln Square',
  sale_price: 88000000,
  utilities_included: null,
  lease_term_min_months: null,
  baths: '4.5',
  price_per_agent: 88000000,
  hoa_fee: 8867,
  corner_lot: null,
  buyers_agent1_email: null,
  image_ids: [],
  pied_a_terre: true,
  commission_remarks: null,
  lease_type: null,
  rebny_id: '1282067',
  listing_price_rounded: '$88.0M',
  must_have_elevator: true,
  ceiling_height: [null, null],
  pct_tax_deductable: 0,
  building_doorman: true,
  listing_price_per_sqft: 13048,
  agent: {
    id: 62643,
    agent_id: null,
    agent_image: null,
    office_phone: '(212) 588-5648',
    rets_agent_id: null,
    rets_office_id: null,
    office_id: null,
    office_name: null,
    first_name: 'Kyle W.',
    last_name: 'Blackmon',
    live: true,
    url: null,
    position: null,
    cell_phone: '',
    company: 'Brown Harris Stevens',
    address1: '',
    address2: null,
    city: '',
    state: '',
    zip: '',
    email: 'kblackmon@bhsusa.com',
    phone: '(212) 588-5648',
    rets_account_active: null,
    created_at: '2017-04-06T18:03:36.560-04:00',
    updated_at: '2019-12-17T03:54:27.411-05:00',
    user_id: null,
    brokerage_id: 6,
    brokerage_name: 'Brown Harris Stevens',
    brokerage_display_name: 'Brown Harris',
    rebny_id: 'RPLU-3242',
    display_name: 'Kyle W. Blackmon',
    rls_unique_id: 'RBNY-34090',
    title: null,
    licensed_as: null,
    team: null,
    test_account: false,
    active: true,
    brokerage_role: null,
    position_title: '',
    license_title: null,
    license_number: '30BL0946787',
    license_state: 'NY',
    social_media: {},
    brokerage_website_username: null,
    specialty_locations: null,
    employment_years: '',
    twitter: null,
    youtube: null,
    linkedin: null,
    facebook: null,
    instagram: null
  },
  building_display_label: '15 Central Park West',
  nearby_transit: {
    mta: [
      {
        distance: 0.06,
        station_name: '59th St-Columbus Circle',
        routes: ['1', 'A', 'C', 'B', 'D']
      },
      {
        distance: 0.08,
        station_name: '59th St',
        routes: ['1', 'A', 'C', 'B', 'D']
      },
      {
        distance: 0.25,
        station_name: '66th St-Lincoln Center',
        routes: ['1']
      },
      {
        distance: 0.29,
        station_name: '57th St',
        routes: ['N', 'Q', 'R']
      },
      {
        distance: 0.42,
        station_name: '72nd St',
        routes: ['C', 'B']
      },
      {
        distance: 0.45,
        station_name: '7th Av',
        routes: ['E', 'B', 'D']
      }
    ]
  },
  price_percent_change: 0,
  must_have_garage: true,
  buyers_agent3_email: null,
  buyers_agent3_id: null,
  building_pets: true,
  south_exposure: null,
  water_source: null,
  borough: '',
  listing_created: null,
  expiration_date: null,
  hoa_fee_formatted: '$8,867',
  buyers_agent1_first_name: null,
  hot_tub: null,
  office_id: null,
  images_processed: true,
  yoga_studio: null,
  community_pool: null,
  slug: 'E0M0N',
  agent_last_name: 'Blackmon',
  buyers_brokerage_display_name: null,
  reindexed_at: '2020-07-30T16:22:23.355-04:00',
  live_work: null,
  developer_brokerage_id: null,
  total_monthlies: 13824,
  floorplan_url_3d: null,
  approval_status: 'Live',
  waterfront_feet: null,
  dishwasher: null,
  entire_building: false,
  foyer: true,
  property_style: null,
  sections: [
    {
      title: 'Features & Amenities',
      type: 'amenities',
      subsections: [
        {
          title: 'Building Amenities',
          elements: [
            {
              title: 'Doorman',
              icon: 'icon-doorman'
            },
            {
              title: 'Elevator',
              icon: 'icon-elevator'
            },
            {
              title: 'Pets',
              icon: 'icon-pets'
            },
            {
              title: 'Pool',
              icon: 'icon-pool'
            },
            {
              title: 'Rooftop',
              icon: 'icon-rooftop'
            },
            {
              title: 'Gym',
              icon: 'icon-gym'
            },
            {
              title: 'Garage',
              icon: 'icon-garage'
            },
            {
              title: 'Building Laundry',
              icon: 'icon-laundry'
            },
            {
              title: 'Concierge',
              icon: 'icon-doorman'
            },
            {
              title: 'Bike Storage',
              icon: 'icon-bicycle'
            },
            {
              title: 'Live-in Super',
              icon: 'icon-super'
            },
            {
              title: 'Building Storage',
              icon: 'icon-storage'
            }
          ]
        },
        {
          title: 'Unit Amenities',
          elements: [
            {
              title: 'Washer Dryer',
              icon: 'icon-laundry'
            },
            {
              title: 'Central AC',
              icon: 'icon-thermometer'
            },
            {
              title: 'Working Fireplace',
              icon: 'icon-fireplace'
            },
            {
              title: 'Terrace',
              icon: 'icon-outdoor-space'
            },
            {
              title: 'Penthouse',
              icon: 'icon-empty'
            },
            {
              title: 'Den',
              icon: 'icon-armchair'
            },
            {
              title: 'Foyer',
              icon: 'icon-empty'
            },
            {
              title: 'Unit Library',
              icon: 'icon-book'
            }
          ]
        }
      ]
    },
    {
      title: 'More Info',
      type: 'more_info',
      subsections: [
        {
          title: 'Listing Information',
          elements: [
            {
              title: 'Available starting',
              value: '11/11/11'
            },
            {
              title: 'Resale',
              value: 'Yes'
            },
            {
              title: 'Monthly Property Taxes',
              value: '$4,957'
            },
            {
              title: 'Monthly Common Charges',
              value: '$8,867'
            },
            {
              title: 'MLS ID',
              value: ''
            },
            {
              title: 'Max Financing Allowed',
              value: '90%'
            }
          ]
        },
        {
          title: 'Neighborhood & School',
          elements: [
            {
              title: 'Cross Streets',
              value: 'West 61st St. and West 62nd St.'
            },
            {
              title: 'Schools',
              value: 'P.S. 452 (K-5)'
            },
            {
              title: 'Location',
              value: 'Lincoln Square'
            },
            {
              title: 'Zip',
              value: '10023'
            },
            {
              title: 'County',
              value: 'New York'
            }
          ]
        },
        {
          title: 'Unit Details',
          elements: [
            {
              title: 'Views',
              value: 'Park, Skyline'
            },
            {
              title: 'Kitchen',
              value: 'Windowed'
            },
            {
              title: 'Floor Number',
              value: '20'
            }
          ]
        },
        {
          title: 'Building & Lot',
          elements: [
            {
              title: 'Condition',
              value: 'mint'
            },
            {
              title: 'Acres',
              value: '1.33'
            },
            {
              title: 'Lot Ft²',
              value: '57,899'
            },
            {
              title: 'Building Class',
              value: 'RM'
            },
            {
              title: 'BBL',
              value: '1011147503'
            },
            {
              title: 'Property Type',
              value: 'Condo'
            }
          ]
        },
        {
          title: 'Policies',
          elements: [
            {
              title: 'Renting Allowed',
              value: 'Yes'
            },
            {
              title: 'Pied-à-Terre Allowed',
              value: 'Yes'
            }
          ]
        }
      ]
    }
  ],
  rls_idx_display: null,
  address_ios: '15 Central Park West',
  open_houses: [
    {
      start_time: '2023-07-05T02:00:00.000-04:00',
      end_time: '2023-07-05T03:00:00.000-04:00',
      by_appointment_only: false,
      public: true
    },
    {
      start_time: '2023-07-05T02:00:00.000-04:00',
      end_time: '2023-07-05T03:00:00.000-04:00',
      by_appointment_only: false,
      public: true
    },
    {
      start_time: '2023-07-05T02:00:00.000-04:00',
      end_time: '2023-07-05T03:00:00.000-04:00',
      by_appointment_only: false,
      public: true
    },
    {
      start_time: '2023-07-05T02:00:00.000-04:00',
      end_time: '2023-07-05T03:00:00.000-04:00',
      by_appointment_only: false,
      public: true
    },
    {
      start_time: '2023-07-05T02:00:00.000-04:00',
      end_time: '2023-07-05T03:00:00.000-04:00',
      by_appointment_only: false,
      public: true
    }
  ],
  buyers_agent1_last_name: null,
  porte_cochere: null,
  basement_type: null,
  sale_listing_price: 88000000,
  lease_term: null,
  mls: null,
  parties: [
    {
      sellers: [
        {
          name: 'WEILL, JOAN HELENE',
          address1: '767 FIFTH AVENUE, 46TH FLOOR',
          address2: null,
          city: 'NEW YORK',
          state: 'NY',
          zip: '10153',
          country: null
        },
        {
          name: 'THE JW REVOCABLE TRUST',
          address1: '767 FIFTH AVENUE, 46TH FLOOR',
          address2: null,
          city: 'NEW YORK',
          state: 'NY',
          zip: '10153',
          country: null
        }
      ],
      buyers: [
        {
          name: 'PROPERTY NY 100-11 LLC',
          address1: 'C/O DAVID A. LIFSON, CPA, CROWE HORWATH LLP',
          address2: '488 MADISON AVENUE, 3RD FLOOR',
          city: 'NEW YORK',
          state: 'NY',
          zip: '10022',
          country: null
        }
      ],
      price: 88000000,
      sale_date: '2012-02-15',
      total_sellers: 2,
      total_buyers: 1,
      unit_number: 'PH20'
    }
  ],
  hardwood_floors: null,
  nearby_stations: [
    {
      distance: '0.0627700072439634',
      station_name: '59th St-Columbus Circle',
      route_1: 'A',
      route_2: 'B',
      route_3: 'C',
      route_4: 'D',
      route_5: '1'
    },
    {
      distance: '0.0815342383442902',
      station_name: '59th St',
      route_1: 'A',
      route_2: 'B',
      route_3: 'C',
      route_4: 'D',
      route_5: '1'
    },
    {
      distance: '0.250223843992568',
      station_name: '66th St-Lincoln Center',
      route_1: '1'
    },
    {
      distance: '0.289650781772652',
      station_name: '57th St',
      route_1: 'N',
      route_2: 'Q',
      route_3: 'R'
    },
    {
      distance: '0.415230920722781',
      station_name: '72nd St',
      route_1: 'B',
      route_2: 'C'
    },
    {
      distance: '0.450410020449377',
      station_name: '7th Av',
      route_1: 'B',
      route_2: 'D',
      route_3: 'E'
    }
  ],
  acres: 1.329178145087236,
  neighborhood: 'Lincoln Square',
  property_type_code: 540,
  brokerage_website: null,
  dog_care: null,
  cul_de_sac: null,
  status_code: 500,
  overall_condition_type: null,
  hidden: false,
  image_list_original: [],
  furnished_rent: null,
  sources: [],
  building_gym: true,
  multilevel: null,
  listing_modified: null,
  monthly_payment_formatted: '$13,824',
  full_floor: null,
  commission_dollar_amount: null,
  contract_price: null,
  buyers_common_agent_ids: [],
  handicap_access: null,
  buyers_agents: [],
  vow_entire_listing_display: false,
  video_url: null,
  pct_tax_deductible_formatted: '0%',
  representation_type: 'exclusive',
  number_of_shares: null,
  is_wide: false,
  developer_email: null,
  neighborhood_id: 51,
  listing_price: 88000000,
  must_have_pool: true,
  parents_for_kids: null,
  virtual_doorman: null,
  agent_ids: [62643],
  num_baths: 4.5,
  similar_geography_ids: [1762, 1739, 1890, 1818, 1862, 1888],
  place_name: 'Lincoln Square',
  waterfront_type: null,
  smoking_allowed: null,
  commission_amount: null,
  waterfront_types: null,
  address_with_unit_number: '15 Central Park West PH20',
  approval: 0,
  override_expired: null,
  available_date: '2011-11-11T00:00:00.000-05:00',
  steam_room: null,
  must_have_gym: true,
  listing_source: 'real_plus',
  water_access: null,
  has_outdoor_space: true,
  pct_tax_deductable_formatted: '0%',
  real_estate_tax_annual: 59484,
  formal_dining_room: null,
  cold_storage: null,
  wooded_lot: null,
  open_house_dates: [
    '2023-07-05T02:00:00.000-04:00',
    '2023-07-05T02:00:00.000-04:00',
    '2023-07-05T02:00:00.000-04:00',
    '2023-07-05T02:00:00.000-04:00',
    '2023-07-05T02:00:00.000-04:00'
  ],
  flip_tax_pct: null,
  dining_room: null,
  buyers_agent4_email: null,
  unit_balcony: false,
  location: {
    lat: 40.769861,
    lon: -73.981389
  },
  image_list: [],
  building_id: 270,
  gated_community: null,
  screening_room: null,
  free_rent: null,
  image_list_large: ['https://assets-staging.perchwell.com/assets/placeholders/condo_wide@2x.png'],
  client_specific_attributes: null,
  vow_address_display: false,
  agent_phone: '(212) 588-5648',
  park_view: true,
  recorded_closing_url:
    'https://a836-acris.nyc.gov/DS/DocumentSearch/DocumentDetail?doc_id=2012021600147001',
  west_exposure: null,
  unit_library: true,
  unit_laundry: true,
  num_rooms: 10,
  penthouse: true,
  building_laundry: true,
  building_storage: true,
  price: '$88.0M',
  brokerage_url: 'http://www.brownharrisstevens.com',
  id: 565618,
  tennis_court: null,
  must_have_doorman: true,
  community_tennis: null,
  zip: '10023',
  catering_kitchen: null,
  geography_ids: [1762, 1333, 1279, 1278],
  list_number: null,
  building_class: 'RM',
  school_ids: [4474],
  neighborhood_name: 'Lincoln Square',
  package_room: null,
  image_list_without_floorplans: [],
  web_id: '',
  real_estate_tax: 4957,
  windowed_kitchen: true,
  main_floor_plan: null,
  ceiling_height_inches: null,
  favorite: false,
  listing_price_per_width: 0,
  flip_tax_amount: null,
  short_description: null,
  city: 'New York',
  created_at: '2018-05-22T02:51:16.984-04:00',
  ceiling_height_feet: null,
  mbr_first_floor: null,
  renting_allowed: true,
  building_garage: true,
  must_have_building_laundry: true,
  is_historical: false,
  library: null,
  sale_date: '2012-02-15T00:00:00.000-05:00',
  pilates_studio: null,
  galley_kitchen: null,
  sides_per_agent: 1,
  unit_id: 817849,
  commission_type: null,
  concierge: true,
  listing_price_per_acre: 66206324.807,
  pool_type: null,
  coexclusive: null,
  buyers_agent4_id: null,
  must_allow_pets: true,
  tagged_item_sections: [
    {
      title: '',
      type: 'tagged-feature-row',
      elements: [
        {
          title: 'Beds',
          value: '4'
        },
        {
          title: 'Baths',
          value: '4½'
        },
        {
          title: 'Rooms',
          value: '10'
        },
        {
          title: 'Ft²',
          value: '6,744'
        }
      ]
    }
  ],
  must_have_outdoor_space: true,
  sale_or_rental: 'S',
  cable_tv: null,
  agents: [
    {
      id: 62643,
      agent_id: null,
      agent_image: null,
      office_phone: '(212) 588-5648',
      rets_agent_id: null,
      rets_office_id: null,
      office_id: null,
      office_name: null,
      first_name: 'Kyle W.',
      last_name: 'Blackmon',
      live: true,
      url: null,
      position: null,
      cell_phone: '',
      company: 'Brown Harris Stevens',
      address1: '',
      address2: null,
      city: '',
      state: '',
      zip: '',
      email: 'kblackmon@bhsusa.com',
      phone: '(212) 588-5648',
      rets_account_active: null,
      created_at: '2017-04-06T18:03:36.560-04:00',
      updated_at: '2019-12-17T03:54:27.411-05:00',
      user_id: null,
      brokerage_id: 6,
      brokerage_name: 'Brown Harris Stevens',
      brokerage_display_name: 'Brown Harris',
      rebny_id: 'RPLU-3242',
      display_name: 'Kyle W. Blackmon',
      rls_unique_id: 'RBNY-34090',
      title: null,
      licensed_as: null,
      team: null,
      test_account: false,
      active: true,
      brokerage_role: null,
      position_title: '',
      license_title: null,
      license_number: '30BL0946787',
      license_state: 'NY',
      social_media: {},
      brokerage_website_username: null,
      specialty_locations: null,
      employment_years: '',
      twitter: null,
      youtube: null,
      linkedin: null,
      facebook: null,
      instagram: null
    }
  ],
  num_units: 230,
  exposures: [],
  depth: 0,
  image_list_thumb: [],
  pct_tax_deductible: 0,
  canonical_neighborhood_id: 51,
  must_have_fireplace: true,
  listing_key: null,
  width: 0,
  address_with_unit_super: '15 Central Park West #PH20',
  is_landmark: null,
  garden: false,
  max_financing_pct: 90,
  automated_parking: null,
  brokerage_id: 6,
  real_estate_tax_formatted: '$4,957',
  cobroke_agreement: null,
  must_have_storage: true,
  num_full_baths: 4,
  original_price: 88000000,
  conference_room: null,
  must_have_rooftop: true,
  bonus: null,
  buyers_brokerage_id: null,
  unit_number: 'PH20',
  east_exposure: null,
  building_elevator: true,
  sqft: 6744,
  wrap_terrace: null,
  locked: true,
  overall_condition: null,
  fuel_type: null,
  building_pool: true,
  longitude: '-73.981389',
  monthly_payment: 13824,
  central_ac: true,
  price_per_buy_side_agent: 0,
  num_stories: 37,
  thumbnail: null,
  loft: null,
  lounge: null,
  garage_type_code: 400,
  spa: null,
  brokerage_name: 'Brown Harris Stevens',
  cross_street_array: ['West 61st St.', 'West 62nd St.'],
  central_park_view: null,
  published: true,
  list_date: '2011-11-11T00:00:00.000-05:00',
  header_info: [
    {
      title: 'Beds',
      value: '4'
    },
    {
      title: 'Baths',
      value: '4½'
    },
    {
      title: 'Rooms',
      value: '10'
    },
    {
      title: 'Ft²',
      value: '6,744'
    },
    {
      title: 'DOM',
      value: '97'
    },
    {
      title: 'Sale Date',
      value: '2/15/12'
    }
  ],
  rental_period_prices: {},
  listing_price_per_br: 22000000,
  percent_of_common_elements: null,
  medium_image: null,
  combined_latitude: 40.769861,
  combined_longitude: -73.981389,
  main_img: 'https://assets-staging.perchwell.com/assets/placeholders/condo_wide@2x.png',
  year_built: 2007,
  nh: 'Lincoln Square',
  floor_plan_list: [],
  status_text: 'Sold',
  unit_garden: false,
  golf_course: null,
  exterior_sqft: null,
  total_monthlies_formatted: '$13,824',
  tax_abatement_notes: null,
  in_law_suite: null,
  agent_email: 'kblackmon@bhsusa.com',
  configuration: null,
  link: '/listings/565618',
  media_room: null,
  newest_date: '2011-11-11T00:00:00.000-05:00',
  building_bike_storage: true,
  guest_suites: null,
  brokerage_display_name: 'Brown Harris',
  contract_date: null,
  tennis_court_types: null,
  building_prewar: false,
  vow_automated_valuation_display: false,
  common_agent_ids: [23632],
  showing_instructions: null,
  board_approval: true,
  mls_zone: null,
  broker_id: null,
  multimedia_list: [],
  listing_price_dollars: '$88,000,000',
  marketing_description: null,
  price_dollars: '$88,000,000',
  property_type_label: null,
  unit_ids: [817849],
  year_last_altered: 2007,
  status_last_changed: '2012-02-15T00:00:00-05:00',
  kitchen_types: ['Windowed'],
  security_system: null,
  sqft_formatted: '6,744',
  building_link: '/building/270-15-central-park-west',
  num_half_baths: 1,
  lot_depth: 346.64,
  region_key: 'nyc',
  lot_width: 232.31,
  is_recently_altered: false,
  website_display_neighborhood: null,
  unit_terrace: true,
  dates_valid: true,
  must_have_unit_laundry: true,
  tax_abatement_expiration_year: null,
  clubhouse: null,
  agent_image: null,
  days_on_market: 97,
  next_open_house: 'Wed, Jul. 5, 2:00-3:00 AM',
  tags: [],
  unit: {
    current_owner: 'PROPERTY NY 100-11 LLC',
    unit_number: 'PH20',
    address_with_unit_hashed: '15 Central Park West #PH20',
    current_listings: [
      {
        status_code: 500,
        status_text: 'Sold 02/15/12',
        id: 565618
      }
    ],
    id: 817849,
    entire_building: false,
    history: {
      sales: [
        {
          listings: [
            {
              id: 565618,
              text: 'Brown Harris'
            }
          ],
          activity: [
            {
              price: 88000000,
              title: 'Active with Brown Harris',
              pct_change: 101.43,
              pct_change_text: 'from last sale',
              time: '2011-11-11T00:00:00.000-05:00',
              terminus: true,
              listing_id: 565618,
              brokerage_id: 6,
              published: true,
              links: []
            },
            {
              price: 88000000,
              title: 'Sold',
              pct_change: 0,
              pct_change_text: '',
              time: '2012-02-15T00:00:00.000-05:00',
              terminus: true,
              listing_id: 565618,
              brokerage_id: 6,
              published: true,
              links: [
                {
                  link_text: 'ACRIS',
                  url:
                    'https://a836-acris.nyc.gov/DS/DocumentSearch/DocumentDetail?doc_id=2012021600147001'
                }
              ]
            }
          ]
        }
      ],
      rentals: []
    }
  },
  other_listings_in_building: [
    {
      building_id: 270,
      listing_price_per_sqft: 11013,
      status_code: 100,
      latitude: '40.769861',
      under_contract: false,
      details_last_updated: '2019-09-11T00:00:00.000-04:00',
      sale_date: null,
      representation_type: 'exclusive',
      property_type: 'Condo',
      listing_price: 65000000,
      sqft: 5902,
      id: 2766570,
      num_bedrooms: 5,
      longitude: '-73.981389',
      monthly_payment: 24013,
      num_baths: 6.5,
      place_name: 'Lincoln Square',
      coexclusive: null,
      address_with_unit: '15 Central Park West PH18/19A',
      address_with_unit_hashed: '15 Central Park West #PH18/19A',
      sale_or_rental: 'S',
      canonical_neighborhood_name: 'Lincoln Square',
      above_area_square_ft: 5902,
      listing_source: 'rls',
      published: true,
      list_date: '2019-09-11T00:00:00.000-04:00',
      price_dollars: '$65,000,000',
      baths: '6.5',
      nh: 'Lincoln Square',
      beds: '5',
      property_type_code: 540,
      brokerage_id: 6,
      next_open_house: {}
    },
    {
      building_id: 270,
      listing_price_per_sqft: 12133,
      status_code: 100,
      latitude: '40.769861',
      under_contract: false,
      details_last_updated: '2019-08-07T00:00:00.000-04:00',
      sale_date: null,
      representation_type: 'exclusive',
      property_type: 'Condo',
      listing_price: 57500000,
      sqft: 4739,
      id: 1429385,
      num_bedrooms: 3,
      longitude: '-73.981389',
      monthly_payment: 19538,
      num_baths: 4.5,
      place_name: 'Lincoln Square',
      coexclusive: null,
      address_with_unit: '15 Central Park West PH43',
      address_with_unit_hashed: '15 Central Park West #PH43',
      sale_or_rental: 'S',
      canonical_neighborhood_name: 'Lincoln Square',
      above_area_square_ft: 4739,
      listing_source: 'rls',
      published: true,
      list_date: '2019-08-07T00:00:00.000-04:00',
      price_dollars: '$57,500,000',
      baths: '4.5',
      nh: 'Lincoln Square',
      beds: '3',
      property_type_code: 540,
      brokerage_id: 1305,
      next_open_house: {}
    },
    {
      building_id: 270,
      listing_price_per_sqft: 11182,
      status_code: 100,
      latitude: '40.769861',
      under_contract: false,
      details_last_updated: '2022-04-26T12:42:44.340-04:00',
      sale_date: null,
      representation_type: 'exclusive',
      property_type: 'Condo',
      listing_price: 45000000,
      sqft: 4024,
      id: 3537973,
      num_bedrooms: 4,
      longitude: '-73.981389',
      monthly_payment: 15851,
      num_baths: 3.5,
      place_name: 'Lincoln Square',
      coexclusive: false,
      address_with_unit: '15 Central Park West PH41',
      address_with_unit_hashed: '15 Central Park West #PH41',
      sale_or_rental: 'S',
      canonical_neighborhood_name: 'Lincoln Square',
      above_area_square_ft: 4024,
      listing_source: 'rls',
      published: true,
      list_date: '2020-03-01T00:00:00.000-05:00',
      price_dollars: '$45,000,000',
      baths: '3.5',
      nh: 'Lincoln Square',
      beds: '4',
      property_type_code: 540,
      brokerage_id: 2111,
      next_open_house: {}
    },
    {
      building_id: 270,
      listing_price_per_sqft: 9597,
      status_code: 100,
      latitude: '40.769861',
      under_contract: false,
      details_last_updated: '2019-06-19T00:00:00.000-04:00',
      sale_date: null,
      representation_type: 'exclusive',
      property_type: 'Condo',
      listing_price: 26500000,
      sqft: 2761,
      id: 1414139,
      num_bedrooms: 3,
      longitude: '-73.981389',
      monthly_payment: 10465,
      num_baths: 3.5,
      place_name: 'Lincoln Square',
      coexclusive: false,
      address_with_unit: '15 Central Park W 34C',
      address_with_unit_hashed: '15 Central Park W #34C',
      sale_or_rental: 'S',
      canonical_neighborhood_name: 'Lincoln Square',
      above_area_square_ft: 2761,
      listing_source: 'reso',
      published: true,
      list_date: '2019-06-19T00:00:00.000-04:00',
      price_dollars: '$26,500,000',
      baths: '3.5',
      nh: 'Lincoln Square',
      beds: '3',
      property_type_code: 540,
      brokerage_id: 6,
      next_open_house: {}
    },
    {
      building_id: 270,
      listing_price_per_sqft: 8373,
      status_code: 100,
      latitude: '40.769861',
      under_contract: false,
      details_last_updated: '2022-04-11T00:00:00.000-04:00',
      sale_date: null,
      representation_type: 'exclusive',
      property_type: 'Condo',
      listing_price: 26000000,
      sqft: 3105,
      id: 3527940,
      num_bedrooms: 3,
      longitude: '-73.981389',
      monthly_payment: 5140,
      num_baths: 3.5,
      place_name: 'Lincoln Square',
      coexclusive: null,
      address_with_unit: '15 Central Park West 37A',
      address_with_unit_hashed: '15 Central Park West #37A',
      sale_or_rental: 'S',
      canonical_neighborhood_name: 'Lincoln Square',
      above_area_square_ft: 3105,
      listing_source: 'reso',
      published: true,
      list_date: '2022-04-11T00:00:00.000-04:00',
      price_dollars: '$26,000,000',
      baths: '3.5',
      nh: 'Lincoln Square',
      beds: '3',
      property_type_code: 540,
      brokerage_id: 26,
      next_open_house: {}
    },
    {
      building_id: 270,
      listing_price_per_sqft: 8373,
      status_code: 100,
      latitude: '40.769861',
      under_contract: false,
      details_last_updated: '2022-04-11T12:21:28.764-04:00',
      sale_date: null,
      representation_type: 'exclusive',
      property_type: 'Condo',
      listing_price: 26000000,
      sqft: 3105,
      id: 3528034,
      num_bedrooms: 3,
      longitude: '-73.981389',
      monthly_payment: 12148,
      num_baths: 3.5,
      place_name: 'Lincoln Square',
      coexclusive: false,
      address_with_unit: '15 Central Park W 37-A',
      address_with_unit_hashed: '15 Central Park W #37-A',
      sale_or_rental: 'S',
      canonical_neighborhood_name: 'Lincoln Square',
      above_area_square_ft: 3105,
      listing_source: 'reso',
      published: true,
      list_date: '2022-04-11T00:00:00.000-04:00',
      price_dollars: '$26,000,000',
      baths: '3.5',
      nh: 'Lincoln Square',
      beds: '3',
      property_type_code: 540,
      brokerage_id: 26,
      next_open_house: {}
    },
    {
      building_id: 270,
      listing_price_per_sqft: 7702,
      status_code: 100,
      latitude: '40.769861',
      under_contract: false,
      details_last_updated: '2019-05-06T12:10:20.413-04:00',
      sale_date: null,
      representation_type: 'exclusive',
      property_type: 'Condo',
      listing_price: 23900000,
      sqft: 3103,
      id: 706233,
      num_bedrooms: 3,
      longitude: '-73.981389',
      monthly_payment: 11821,
      num_baths: 3.5,
      place_name: 'Lincoln Square',
      coexclusive: null,
      address_with_unit: '15 Central Park West 34-A',
      address_with_unit_hashed: '15 Central Park West #34-A',
      sale_or_rental: 'S',
      canonical_neighborhood_name: 'Lincoln Square',
      above_area_square_ft: 3103,
      listing_source: 'rls',
      published: true,
      list_date: '2018-09-06T00:00:00.000-04:00',
      price_dollars: '$23,900,000',
      baths: '3.5',
      nh: 'Lincoln Square',
      beds: '3',
      property_type_code: 540,
      brokerage_id: 26,
      next_open_house: {}
    },
    {
      building_id: 270,
      listing_price_per_sqft: 6585,
      status_code: 100,
      latitude: '40.769861',
      under_contract: false,
      details_last_updated: '2019-05-06T12:23:32.574-04:00',
      sale_date: null,
      representation_type: 'exclusive',
      property_type: 'Condo',
      listing_price: 21950000,
      sqft: 3333,
      id: 776208,
      num_bedrooms: 4,
      longitude: '-73.981389',
      monthly_payment: 12650,
      num_baths: 4.5,
      place_name: 'Lincoln Square',
      coexclusive: null,
      address_with_unit: '15 Central Park West 6D',
      address_with_unit_hashed: '15 Central Park West #6D',
      sale_or_rental: 'S',
      canonical_neighborhood_name: 'Lincoln Square',
      above_area_square_ft: 3333,
      listing_source: 'rls',
      published: true,
      list_date: '2019-03-20T00:00:00.000-04:00',
      price_dollars: '$21,950,000',
      baths: '4.5',
      nh: 'Lincoln Square',
      beds: '4',
      property_type_code: 540,
      brokerage_id: 2111,
      next_open_house: {}
    },
    {
      building_id: 270,
      listing_price_per_sqft: 7153,
      status_code: 100,
      latitude: '40.769861',
      under_contract: false,
      details_last_updated: '2022-01-29T07:53:47.652-05:00',
      sale_date: null,
      representation_type: 'exclusive',
      property_type: 'Condo',
      listing_price: 19750000,
      sqft: 2761,
      id: 3519738,
      num_bedrooms: 3,
      longitude: '-73.981389',
      monthly_payment: 10946,
      num_baths: 3.5,
      place_name: 'Lincoln Square',
      coexclusive: false,
      address_with_unit: '15 Central Park W 32C',
      address_with_unit_hashed: '15 Central Park W #32C',
      sale_or_rental: 'S',
      canonical_neighborhood_name: 'Lincoln Square',
      above_area_square_ft: 2761,
      listing_source: 'rls',
      published: true,
      list_date: '2021-12-03T00:00:00.000-05:00',
      price_dollars: '$19,750,000',
      baths: '3.5',
      nh: 'Lincoln Square',
      beds: '3',
      property_type_code: 540,
      brokerage_id: 1787,
      next_open_house: {}
    },
    {
      building_id: 270,
      listing_price_per_sqft: 7139,
      status_code: 100,
      latitude: '40.769861',
      under_contract: false,
      details_last_updated: '2019-04-05T11:09:48.497-04:00',
      sale_date: null,
      representation_type: 'exclusive',
      property_type: 'Condo',
      listing_price: 16900000,
      sqft: 2367,
      id: 617545,
      num_bedrooms: 2,
      longitude: '-73.981389',
      monthly_payment: 8245,
      num_baths: 2.5,
      place_name: 'Lincoln Square',
      coexclusive: false,
      address_with_unit: '15 Central Park West 26B',
      address_with_unit_hashed: '15 Central Park West #26B',
      sale_or_rental: 'S',
      canonical_neighborhood_name: 'Lincoln Square',
      above_area_square_ft: 2367,
      listing_source: 'perchwell',
      published: true,
      list_date: '2018-07-09T16:18:01.455-04:00',
      price_dollars: '$16,900,000',
      baths: '2.5',
      nh: 'Lincoln Square',
      beds: '2',
      property_type_code: 540,
      brokerage_id: 1824,
      next_open_house: {}
    },
    {
      building_id: 270,
      listing_price_per_sqft: 6717,
      status_code: 100,
      latitude: '40.769861',
      under_contract: false,
      details_last_updated: '2019-12-09T13:56:58.853-05:00',
      sale_date: null,
      representation_type: 'exclusive',
      property_type: 'Condo',
      listing_price: 15900000,
      sqft: 2367,
      id: 2819330,
      num_bedrooms: 2,
      longitude: '-73.981389',
      monthly_payment: 8248,
      num_baths: 2.5,
      place_name: 'Lincoln Square',
      coexclusive: null,
      address_with_unit: '15 Central Park West 27B',
      address_with_unit_hashed: '15 Central Park West #27B',
      sale_or_rental: 'S',
      canonical_neighborhood_name: 'Lincoln Square',
      above_area_square_ft: 2367,
      listing_source: 'rls',
      published: true,
      list_date: '2019-11-19T00:00:00.000-05:00',
      price_dollars: '$15,900,000',
      baths: '2.5',
      nh: 'Lincoln Square',
      beds: '2',
      property_type_code: 540,
      brokerage_id: 1305,
      next_open_house: {}
    },
    {
      building_id: 270,
      listing_price_per_sqft: 6273,
      status_code: 100,
      latitude: '40.769861',
      under_contract: false,
      details_last_updated: '2022-04-26T12:42:11.502-04:00',
      sale_date: null,
      representation_type: 'exclusive',
      property_type: 'Condo',
      listing_price: 14850000,
      sqft: 2367,
      id: 3537970,
      num_bedrooms: 2,
      longitude: '-73.981389',
      monthly_payment: 8426,
      num_baths: 2.5,
      place_name: 'Lincoln Square',
      coexclusive: false,
      address_with_unit: '15 Central Park West 27B',
      address_with_unit_hashed: '15 Central Park West #27B',
      sale_or_rental: 'S',
      canonical_neighborhood_name: 'Lincoln Square',
      above_area_square_ft: 2367,
      listing_source: 'rls',
      published: true,
      list_date: '2022-04-26T00:00:00.000-04:00',
      price_dollars: '$14,850,000',
      baths: '2.5',
      nh: 'Lincoln Square',
      beds: '2',
      property_type_code: 540,
      brokerage_id: 2111,
      next_open_house: {}
    },
    {
      building_id: 270,
      listing_price_per_sqft: 5702,
      status_code: 100,
      latitude: '40.769861',
      under_contract: false,
      details_last_updated: '2019-11-02T10:10:28.047-04:00',
      sale_date: null,
      representation_type: 'exclusive',
      property_type: 'Condo',
      listing_price: 9900000,
      sqft: 1736,
      id: 2766452,
      num_bedrooms: 2,
      longitude: '-73.981389',
      monthly_payment: 6608,
      num_baths: 2.5,
      place_name: 'Lincoln Square',
      coexclusive: null,
      address_with_unit: '15 Central Park West 25-B',
      address_with_unit_hashed: '15 Central Park West #25-B',
      sale_or_rental: 'S',
      canonical_neighborhood_name: 'Lincoln Square',
      above_area_square_ft: 1736,
      listing_source: 'rls',
      published: true,
      list_date: '2019-09-10T00:00:00.000-04:00',
      price_dollars: '$9,900,000',
      baths: '2.5',
      nh: 'Lincoln Square',
      beds: '2',
      property_type_code: 540,
      brokerage_id: 26,
      next_open_house: {}
    },
    {
      building_id: 270,
      listing_price_per_sqft: 3532,
      status_code: 100,
      latitude: '40.769861',
      under_contract: false,
      details_last_updated: '2018-04-21T00:00:00.000-04:00',
      sale_date: null,
      representation_type: 'exclusive',
      property_type: 'Condo',
      listing_price: 6800000,
      sqft: 1925,
      id: 1421261,
      num_bedrooms: 2,
      longitude: '-73.981389',
      monthly_payment: 7295,
      num_baths: 2,
      place_name: 'Lincoln Square',
      coexclusive: null,
      address_with_unit: '15 Central Park West 12-L',
      address_with_unit_hashed: '15 Central Park West #12-L',
      sale_or_rental: 'S',
      canonical_neighborhood_name: 'Lincoln Square',
      above_area_square_ft: 1925,
      listing_source: 'rls',
      published: true,
      list_date: '2018-04-21T00:00:00.000-04:00',
      price_dollars: '$6,800,000',
      baths: '2',
      nh: 'Lincoln Square',
      beds: '2',
      property_type_code: 540,
      brokerage_id: 26,
      next_open_house: {}
    },
    {
      building_id: 270,
      listing_price_per_sqft: 3767,
      status_code: 100,
      latitude: '40.769861',
      under_contract: false,
      details_last_updated: '2019-09-24T09:41:52.783-04:00',
      sale_date: null,
      representation_type: 'exclusive',
      property_type: 'Condo',
      listing_price: 6495000,
      sqft: 1724,
      id: 770089,
      num_bedrooms: 2,
      longitude: '-73.981389',
      monthly_payment: 5924,
      num_baths: 2.5,
      place_name: 'Lincoln Square',
      coexclusive: null,
      address_with_unit: '15 Central Park West 11M',
      address_with_unit_hashed: '15 Central Park West #11M',
      sale_or_rental: 'S',
      canonical_neighborhood_name: 'Lincoln Square',
      above_area_square_ft: 1724,
      listing_source: 'rls',
      published: true,
      list_date: '2019-02-28T00:00:00.000-05:00',
      price_dollars: '$6,495,000',
      baths: '2.5',
      nh: 'Lincoln Square',
      beds: '2',
      property_type_code: 540,
      brokerage_id: 6,
      next_open_house: {}
    },
    {
      building_id: 270,
      listing_price_per_sqft: 3218,
      status_code: 100,
      latitude: '40.769861',
      under_contract: false,
      details_last_updated: '2021-02-05T13:58:57.952-05:00',
      sale_date: null,
      representation_type: 'exclusive',
      property_type: 'Condo',
      listing_price: 6395000,
      sqft: 1987,
      id: 3512618,
      num_bedrooms: 2,
      longitude: '-73.981389',
      monthly_payment: 7611,
      num_baths: 2.5,
      place_name: 'Lincoln Square',
      coexclusive: false,
      address_with_unit: '15 Central Park W 3-F',
      address_with_unit_hashed: '15 Central Park W #3-F',
      sale_or_rental: 'S',
      canonical_neighborhood_name: 'Lincoln Square',
      above_area_square_ft: 1987,
      listing_source: 'reso',
      published: true,
      list_date: '2020-02-21T00:00:00.000-05:00',
      price_dollars: '$6,395,000',
      baths: '2.5',
      nh: 'Lincoln Square',
      beds: '2',
      property_type_code: 540,
      brokerage_id: 26,
      next_open_house: {}
    },
    {
      building_id: 270,
      listing_price_per_sqft: 3683,
      status_code: 100,
      latitude: '40.769861',
      under_contract: false,
      details_last_updated: '2017-02-06T00:00:00.000-05:00',
      sale_date: null,
      representation_type: 'exclusive',
      property_type: 'Condo',
      listing_price: 6350000,
      sqft: 1724,
      id: 2821701,
      num_bedrooms: 2,
      longitude: '-73.981389',
      monthly_payment: 6478,
      num_baths: 2.5,
      place_name: 'Lincoln Square',
      coexclusive: null,
      address_with_unit: '15 Central Park West 16-M',
      address_with_unit_hashed: '15 Central Park West #16-M',
      sale_or_rental: 'S',
      canonical_neighborhood_name: 'Lincoln Square',
      above_area_square_ft: 1724,
      listing_source: 'rls',
      published: true,
      list_date: '2017-02-06T00:00:00.000-05:00',
      price_dollars: '$6,350,000',
      baths: '2.5',
      nh: 'Lincoln Square',
      beds: '2',
      property_type_code: 540,
      brokerage_id: 1899,
      next_open_house: {}
    },
    {
      building_id: 270,
      listing_price_per_sqft: 3353,
      status_code: 100,
      latitude: '40.769861',
      under_contract: false,
      details_last_updated: '2022-03-31T00:00:00.000-04:00',
      sale_date: null,
      representation_type: 'exclusive',
      property_type: 'Condo',
      listing_price: 4500000,
      sqft: 1342,
      id: 3521270,
      num_bedrooms: 1,
      longitude: '-73.981389',
      monthly_payment: 2217,
      num_baths: 2,
      place_name: 'Lincoln Square',
      coexclusive: null,
      address_with_unit: '15 Central Park W 16H',
      address_with_unit_hashed: '15 Central Park W #16H',
      sale_or_rental: 'S',
      canonical_neighborhood_name: 'Lincoln Square',
      above_area_square_ft: 1342,
      listing_source: 'reso',
      published: true,
      list_date: '2022-03-31T00:00:00.000-04:00',
      price_dollars: '$4,500,000',
      baths: '2',
      nh: 'Lincoln Square',
      beds: '1',
      property_type_code: 540,
      brokerage_id: 26,
      next_open_house: {}
    },
    {
      building_id: 270,
      listing_price_per_sqft: 3353,
      status_code: 100,
      latitude: '40.769861',
      under_contract: false,
      details_last_updated: '2022-03-31T12:41:11.215-04:00',
      sale_date: null,
      representation_type: 'exclusive',
      property_type: 'Condo',
      listing_price: 4500000,
      sqft: 1342,
      id: 289889,
      num_bedrooms: 1,
      longitude: '-73.981389',
      monthly_payment: 5248,
      num_baths: 2,
      place_name: 'Lincoln Square',
      coexclusive: false,
      address_with_unit: '15 Central Park W 16-H',
      address_with_unit_hashed: '15 Central Park W #16-H',
      sale_or_rental: 'S',
      canonical_neighborhood_name: 'Lincoln Square',
      above_area_square_ft: 1342,
      listing_source: 'reso',
      published: true,
      list_date: '2022-03-31T00:00:00.000-04:00',
      price_dollars: '$4,500,000',
      baths: '2',
      nh: 'Lincoln Square',
      beds: '1',
      property_type_code: 540,
      brokerage_id: 26,
      next_open_house: {}
    },
    {
      building_id: 270,
      listing_price_per_sqft: 235,
      status_code: 100,
      latitude: '40.769861',
      under_contract: false,
      details_last_updated: '2022-04-15T00:00:00.000-04:00',
      sale_date: null,
      representation_type: 'exclusive',
      property_type: 'Condo',
      listing_price: 66000,
      sqft: 3364,
      id: 3530379,
      num_bedrooms: 4,
      longitude: '-73.981389',
      monthly_payment: 66000,
      num_baths: 3.5,
      place_name: 'Lincoln Square',
      coexclusive: false,
      address_with_unit: '15 Central Park W 15B',
      address_with_unit_hashed: '15 Central Park W #15B',
      sale_or_rental: 'R',
      canonical_neighborhood_name: 'Lincoln Square',
      above_area_square_ft: 3364,
      listing_source: 'rls',
      published: true,
      list_date: '2022-04-15T00:00:00.000-04:00',
      price_dollars: '$66,000',
      baths: '3.5',
      nh: 'Lincoln Square',
      beds: '4',
      property_type_code: 540,
      brokerage_id: 1305,
      next_open_house: {}
    },
    {
      building_id: 270,
      listing_price_per_sqft: 226,
      status_code: 100,
      latitude: '40.769861',
      under_contract: false,
      details_last_updated: '2019-06-25T13:12:23.422-04:00',
      sale_date: null,
      representation_type: 'exclusive',
      property_type: 'Condo',
      listing_price: 60000,
      sqft: 3176,
      id: 168225,
      num_bedrooms: 3,
      longitude: '-73.981389',
      monthly_payment: 60000,
      num_baths: 4,
      place_name: 'Lincoln Square',
      coexclusive: null,
      address_with_unit: '15 Central Park West 28-D',
      address_with_unit_hashed: '15 Central Park West #28-D',
      sale_or_rental: 'R',
      canonical_neighborhood_name: 'Lincoln Square',
      above_area_square_ft: 3176,
      listing_source: 'rls',
      published: true,
      list_date: '2017-07-24T00:00:00.000-04:00',
      price_dollars: '$60,000',
      baths: '4',
      nh: 'Lincoln Square',
      beds: '3',
      property_type_code: 540,
      brokerage_id: 26,
      next_open_house: {}
    },
    {
      building_id: 270,
      listing_price_per_sqft: 217,
      status_code: 100,
      latitude: '40.769861',
      under_contract: false,
      details_last_updated: '2022-04-16T00:00:00.000-04:00',
      sale_date: null,
      representation_type: 'exclusive',
      property_type: 'Condo',
      listing_price: 50000,
      sqft: 2761,
      id: 3530874,
      num_bedrooms: 3,
      longitude: '-73.981389',
      monthly_payment: 50000,
      num_baths: 3.5,
      place_name: 'Lincoln Square',
      coexclusive: false,
      address_with_unit: '15 Central Park W 32C',
      address_with_unit_hashed: '15 Central Park W #32C',
      sale_or_rental: 'R',
      canonical_neighborhood_name: 'Lincoln Square',
      above_area_square_ft: 2761,
      listing_source: 'reso',
      published: true,
      list_date: '2022-04-16T00:00:00.000-04:00',
      price_dollars: '$50,000',
      baths: '3.5',
      nh: 'Lincoln Square',
      beds: '3',
      property_type_code: 540,
      brokerage_id: 1787,
      next_open_house: {}
    },
    {
      building_id: 270,
      listing_price_per_sqft: 152,
      status_code: 100,
      latitude: '40.769861',
      under_contract: false,
      details_last_updated: '2021-02-05T13:58:09.179-05:00',
      sale_date: null,
      representation_type: 'exclusive',
      property_type: 'Condo',
      listing_price: 35000,
      sqft: 2761,
      id: 769986,
      num_bedrooms: 3,
      longitude: '-73.981389',
      monthly_payment: 35000,
      num_baths: 3.5,
      place_name: 'Lincoln Square',
      coexclusive: false,
      address_with_unit: '15 Central Park W 34C',
      address_with_unit_hashed: '15 Central Park W #34C',
      sale_or_rental: 'R',
      canonical_neighborhood_name: 'Lincoln Square',
      above_area_square_ft: 2761,
      listing_source: 'reso',
      published: true,
      list_date: '2019-02-28T00:00:00.000-05:00',
      price_dollars: '$35,000',
      baths: '3.5',
      nh: 'Lincoln Square',
      beds: '3',
      property_type_code: 540,
      brokerage_id: 6,
      next_open_house: {}
    },
    {
      building_id: 270,
      listing_price_per_sqft: 177,
      status_code: 100,
      latitude: '40.769861',
      under_contract: false,
      details_last_updated: '2019-12-05T00:00:00.000-05:00',
      sale_date: null,
      representation_type: 'exclusive',
      property_type: 'Condo',
      listing_price: 35000,
      sqft: 2367,
      id: 2823517,
      num_bedrooms: 2,
      longitude: '-73.981389',
      monthly_payment: 35000,
      num_baths: 3,
      place_name: 'Lincoln Square',
      coexclusive: null,
      address_with_unit: '15 Central Park West 27B',
      address_with_unit_hashed: '15 Central Park West #27B',
      sale_or_rental: 'R',
      canonical_neighborhood_name: 'Lincoln Square',
      above_area_square_ft: 2367,
      listing_source: 'rls',
      published: true,
      list_date: '2019-12-05T00:00:00.000-05:00',
      price_dollars: '$35,000',
      baths: '3',
      nh: 'Lincoln Square',
      beds: '2',
      property_type_code: 540,
      brokerage_id: 1305,
      next_open_house: {}
    },
    {
      building_id: 270,
      listing_price_per_sqft: 164,
      status_code: 100,
      latitude: '40.769861',
      under_contract: false,
      details_last_updated: '2019-11-11T09:24:36.473-05:00',
      sale_date: null,
      representation_type: 'exclusive',
      property_type: 'Condo',
      listing_price: 32500,
      sqft: 2367,
      id: 1447223,
      num_bedrooms: 2,
      longitude: '-73.981389',
      monthly_payment: 32500,
      num_baths: 2.5,
      place_name: 'Lincoln Square',
      coexclusive: false,
      address_with_unit: '15 Central Park West 26B',
      address_with_unit_hashed: '15 Central Park West #26B',
      sale_or_rental: 'R',
      canonical_neighborhood_name: 'Lincoln Square',
      above_area_square_ft: 2367,
      listing_source: 'perchwell',
      published: true,
      list_date: '2019-08-30T09:14:20.721-04:00',
      price_dollars: '$32,500',
      baths: '2.5',
      nh: 'Lincoln Square',
      beds: '2',
      property_type_code: 540,
      brokerage_id: 1824,
      next_open_house: {}
    },
    {
      building_id: 270,
      listing_price_per_sqft: 107,
      status_code: 100,
      latitude: '40.769861',
      under_contract: false,
      details_last_updated: '2019-11-19T00:00:00.000-05:00',
      sale_date: null,
      representation_type: 'exclusive',
      property_type: 'Condo',
      listing_price: 15500,
      sqft: 1724,
      id: 2819550,
      num_bedrooms: 2,
      longitude: '-73.981389',
      monthly_payment: 15500,
      num_baths: 2.5,
      place_name: 'Lincoln Square',
      coexclusive: null,
      address_with_unit: '15 Central Park West 16-M',
      address_with_unit_hashed: '15 Central Park West #16-M',
      sale_or_rental: 'R',
      canonical_neighborhood_name: 'Lincoln Square',
      above_area_square_ft: 1724,
      listing_source: 'rls',
      published: true,
      list_date: '2019-11-19T00:00:00.000-05:00',
      price_dollars: '$15,500',
      baths: '2.5',
      nh: 'Lincoln Square',
      beds: '2',
      property_type_code: 540,
      brokerage_id: 1899,
      next_open_house: {}
    },
    {
      building_id: 270,
      listing_price_per_sqft: 126,
      status_code: 240,
      latitude: '40.769861',
      under_contract: true,
      details_last_updated: '2022-03-14T08:50:45.631-04:00',
      sale_date: null,
      representation_type: 'exclusive',
      property_type: 'Condo',
      listing_price: 15000,
      sqft: 1422,
      id: 3520079,
      num_bedrooms: 2,
      longitude: '-73.981389',
      monthly_payment: 15000,
      num_baths: 2.5,
      place_name: 'Lincoln Square',
      coexclusive: false,
      address_with_unit: '15 Central Park W 24F',
      address_with_unit_hashed: '15 Central Park W #24F',
      sale_or_rental: 'R',
      canonical_neighborhood_name: 'Lincoln Square',
      above_area_square_ft: 1422,
      listing_source: 'reso',
      published: true,
      list_date: '2022-03-14T00:00:00.000-04:00',
      price_dollars: '$15,000',
      baths: '2.5',
      nh: 'Lincoln Square',
      beds: '2',
      property_type_code: 540,
      brokerage_id: 1305,
      next_open_house: {}
    },
    {
      building_id: 270,
      listing_price_per_sqft: 107,
      status_code: 240,
      latitude: '40.769861',
      under_contract: true,
      details_last_updated: '2019-11-27T11:20:27.978-05:00',
      sale_date: null,
      representation_type: 'exclusive',
      property_type: 'Condo',
      listing_price: 12000,
      sqft: 1342,
      id: 2809006,
      num_bedrooms: 1,
      longitude: '-73.981389',
      monthly_payment: 12000,
      num_baths: 2,
      place_name: 'Lincoln Square',
      coexclusive: false,
      address_with_unit: '15 Central Park West 15J',
      address_with_unit_hashed: '15 Central Park West #15J',
      sale_or_rental: 'R',
      canonical_neighborhood_name: 'Lincoln Square',
      above_area_square_ft: 1342,
      listing_source: 'perchwell',
      published: true,
      list_date: '2019-10-26T15:09:48.089-04:00',
      price_dollars: '$12,000',
      baths: '2',
      nh: 'Lincoln Square',
      beds: '1',
      property_type_code: 540,
      brokerage_id: 1683,
      next_open_house: {}
    },
    {
      building_id: 270,
      listing_price_per_sqft: 107,
      status_code: 100,
      latitude: '40.769861',
      under_contract: false,
      details_last_updated: '2019-12-15T00:00:00.000-05:00',
      sale_date: null,
      representation_type: 'exclusive',
      property_type: 'Condo',
      listing_price: 12000,
      sqft: 1343,
      id: 2828406,
      num_bedrooms: 1,
      longitude: '-73.981389',
      monthly_payment: 12000,
      num_baths: 2,
      place_name: 'Lincoln Square',
      coexclusive: null,
      address_with_unit: '15 Central Park West 16H',
      address_with_unit_hashed: '15 Central Park West #16H',
      sale_or_rental: 'R',
      canonical_neighborhood_name: 'Lincoln Square',
      above_area_square_ft: 1343,
      listing_source: 'rls',
      published: true,
      list_date: '2019-12-15T00:00:00.000-05:00',
      price_dollars: '$12,000',
      baths: '2',
      nh: 'Lincoln Square',
      beds: '1',
      property_type_code: 540,
      brokerage_id: 1305,
      next_open_house: {}
    }
  ],
  similar_listings: null
};
